name: Code coverage

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
          extensions: 'mbstring, openssl, zip'
          tools: 'composer:v1'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: composer install --ansi --no-interaction --no-progress --no-suggest --optimize-autoloader
      - name: Perform tests (with code coverage)
        run: composer run-script test -- --verbose --do-not-cache-result --coverage-clover code-coverage.xml
      - name: Upload code coverage
        uses: codecov/codecov-action@v1
        with:
          file: code-coverage.xml
          flags: unittests
