name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        php-version:
          - '7.2'
          - '7.3'
          - '7.4'
    name: PHP ${{ matrix.php-version }} on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    if: "!startsWith(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: 'mbstring, openssl, zip'
          tools: 'composer:v1'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: composer install --no-progress --no-suggest --optimize-autoloader --ansi --no-interaction
      - name: Perform tests
        if: matrix.operating-system != 'ubuntu-latest' || matrix.php-version != '7.2'
        run: composer run-script test -- --verbose --do-not-cache-result
      - name: Perform tests (with code coverage)
        if: matrix.operating-system == 'ubuntu-latest' && matrix.php-version == '7.2'
        run: composer run-script test -- --verbose --do-not-cache-result --coverage-clover code-coverage.xml
      - name: Upload code coverage
        if: matrix.operating-system == 'ubuntu-latest' && matrix.php-version == '7.2'
        uses: codecov/codecov-action@v1
        with:
          file: code-coverage.xml
          flags: unittests
